from include.variables import *

PRESENCE_MSG_CLIENT = [
    ACTION,
    TIME,
    TYPE,
    USER,
]

SERVER_RESPONSE_OK = {
    RESPONSE: RESPONSE_OK,
    ALERT: RESPONSE_OK_TEXT
}

SERVER_RESPONSE_BAD_REQUEST = {
    RESPONSE: RESPONSE_BAD_REQUEST,
    ALERT: RESPONSE_BAD_REQUEST_TEXT
}

SERVER_RESPONSE_SERVER_ERROR = {
    RESPONSE: RESPONSE_SERVER_ERROR,
}